theme: jekyll-theme-midnight
title: blog.codemartin.com
email: martindye@btinternet.com
description: things to bring you joy
repository: blog.codemartin.com/martindye
timezone: Europe/London
show_header: false
url: "https://blog.codemartin.com" # the base hostname & protocol for site
plugins:
  - jekyll-sitemap